# Generated by Django 5.1.15 on 2026-03-30 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                ("avg_time_on_page", models.FloatField(blank=True, null=True)),
                ("bounce_rate", models.FloatField(blank=True, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_snapshots",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("post", "date")},
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("session_id", models.CharField(max_length=64)),
                ("referrer", models.URLField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_hash", models.CharField(max_length=64)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="analytics_p_created_44ec6b_idx"
                    ),
                    models.Index(
                        fields=["post", "-created_at"],
                        name="analytics_p_post_id_784ecb_idx",
                    ),
                    models.Index(
                        fields=["session_id"], name="analytics_p_session_a580f2_idx"
                    ),
                ],
            },
        ),
    ]
