# Generated by Django 5.1.15 on 2026-04-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image_external_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
