# Generated by Django 5.1.15 on 2026-03-30 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media_library", "0001_initial"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("og_title", models.CharField(blank=True, max_length=70)),
                ("og_description", models.CharField(blank=True, max_length=200)),
                ("canonical_url", models.URLField(blank=True)),
                ("no_index", models.BooleanField(default=False)),
                ("structured_data", models.JSONField(blank=True, default=dict)),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media_library.mediaasset",
                    ),
                ),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_metadata",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Metadata",
                "verbose_name_plural": "SEO Metadata",
            },
        ),
    ]
